// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://fpwwljcortcssldjqluy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZwd3dsamNvcnRjc3NsZGpxbHV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQwOTQxNzUsImV4cCI6MjA3OTY3MDE3NX0.zQbdsORYnLLTSSedDqwc6YJidVoeueYRvrdearjFvr0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);