// This file is usually generated by the Supabase CLI.
// It contains the TypeScript definitions for your database schema.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      // Existing tables (partial definition for required fields)
      p_trab: {
        Row: {
          id: string
          user_id: string
          numero_ptrab: string | null
          nome_operacao: string
          periodo_inicio: string
          periodo_fim: string
          efetivo_empregado: string
          acoes: string | null
          status: string
          // ... other columns
        }
        Insert: {
          // ...
        }
        Update: {
          // ...
        }
        Relationships: []
      }
      diretrizes_concessionaria: {
        Row: {
          id: string
          user_id: string
          ano_referencia: number
          categoria: string // 'AGUA_ESGOTO' | 'ENERGIA_ELETRICA'
          nome_concessionaria: string
          consumo_pessoa_dia: number
          custo_unitario: number
          unidade_custo: string
          // ... other columns
        }
        Insert: {
          // ...
        }
        Update: {
          // ...
        }
        Relationships: []
      }
      concessionaria_registros: { // NEW TABLE DEFINITION
        Row: {
          id: string
          p_trab_id: string
          diretriz_id: string
          organizacao: string
          ug: string
          om_detentora: string | null
          ug_detentora: string | null
          dias_operacao: number
          efetivo: number
          categoria: string
          valor_unitario: number
          consumo_pessoa_dia: number
          valor_total: number
          valor_nd_39: number
          detalhamento: string | null
          detalhamento_customizado: string | null
          fase_atividade: string | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          p_trab_id: string
          diretriz_id: string
          organizacao: string
          ug: string
          om_detentora?: string | null
          ug_detentora?: string | null
          dias_operacao?: number
          efetivo?: number
          categoria: string
          valor_unitario: number
          consumo_pessoa_dia: number
          valor_total: number
          valor_nd_39: number
          detalhamento?: string | null
          detalhamento_customizado?: string | null
          fase_atividade?: string | null
        }
        Update: {
          // ...
        }
        Relationships: [
          {
            foreignKeyName: "concessionaria_registros_diretriz_id_fkey"
            columns: ["diretriz_id"]
            isOneToOne: false
            referencedRelation: "diretrizes_concessionaria"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "concessionaria_registros_p_trab_id_fkey"
            columns: ["p_trab_id"]
            isOneToOne: false
            referencedRelation: "p_trab"
            referencedColumns: ["id"]
          },
        ]
      }
      // ... other tables
    }
    Views: {
      // ...
    }
    Functions: {
      // ...
    }
    Enums: {
      // ...
    }
    CompositeTypes: {
      // ...
    }
  }
}